### ISSUE TITLE
Create a command to start the Chained VNF test case on OpenStack

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#108]
TBD

Description: One script that sets up networking, deploys VNFs and connects them in a chain

**Comment by taylor** [comment]
This is related to implementing the [VNF chained router test case](#175) on OpenStack

**Comment by robertstarmer** [comment]
Current steps:
1. Set up networks with [create_vlans.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/VNF_openstack/create_vlans.sh)
1. Run test setup script (launces VMs) [create_instance_triple_port.sh](https://github.com/cncf/cnf-testbed/blob/master/comparison/kubecon18-chained_nf_test/VNF_openstack/create_instance_triple_port.sh)

- [ ] Need to document naming of networks and likley launch process and integrate into a single script.
- [ ] Investigate passing in attached networks from the initial terraform/ansible deployment to further automate network creation.

@taylor @michaelspedersen @denverwilliams @bvera
