### ISSUE TITLE
Display 1 throughput performance number from the comparison of CNF for K8s and 1 for VNF on Openstack

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#112]
- [ ] Show performance metric by programmatically extracting results from NFVbench and computing a single performance metric

- [x] TODO: Write-up requirements for performance metric desired in a github ticket. Give requirements to Peter (and Michael) to provide feedback on programmatic access to the NFVbench result data.

**Comment by pmikus** [comment]
I would prefer simple way (from repo):
NDR numbers
`$ pushd comparison/baseline_nf_performance/results/; fgrep -R "| NDR |" * | sort | awk -F '[ ]*[|][ ]*' '{print $1 " " $5 " (" $4 ")"}'; popd`

MRR numbers
`$pushd comparison/baseline_nf_performance/results/; fgrep -R "|    Total    |" * | sort | awk -F '[ ]*[|][ ]*' '{print $1 " " $8 " (" $5 ")"}'; popd`

Depends where the number would be use we can decorate later. Having precisely named directories will print nice output?

**Comment by taylor** [comment]
Also reference issue #86 ([CSIT Testbench] summarize throughput results)

**Comment by michaelspedersen** [comment]
Results added in previous commit:
```
1chain1nodeness: 7.0061 Gbps (10,425,713 pps)
1chain2nodeness: 6.4431 Gbps (9,588,019 pps)
1chain4nodeness: 5.9264 Gbps (8,819,001 pps)
1chain7nodeness: 4.3944 Gbps (6,539,262 pps)

2chain1nodeness: 5.9686 Gbps (8,881,836 pps)
2chain2nodeness: 5.7651 Gbps (8,579,009 pps)
2chain3nodeness: 5.6016 Gbps (8,335,754 pps)

3chain1nodeness: 5.7067 Gbps (8,492,092 pps)
3chain2nodeness: 5.4993 Gbps (8,183,459 pps)
```

**Comment by taylor** [comment]
Results and requirements for OpenStack and K8s on Mellanox NICs:
- OpenStack https://github.com/cncf/cnf-testbed/issues/199#issuecomment-466411842
- K8s https://github.com/cncf/cnf-testbed/issues/191#issuecomment-466640134

Skipped: 
- Programmatically pulling results from nfvbench machine
  * Will look at options including dynamic visualization Alec and Michael have discussed as well as a Intel data-replays the data in the visualizer
