### ISSUE TITLE
Upgrade ansible to version 2.3.1.0 or later to resolve moderate security vulnerability

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#126]
https://github.com/cncf/cnfs/network/alert/comparison/ansible/roles/retr0h.etcd/requirements.txt/ansible/open

Remediation:

Upgrade ansible to version 2.3.1.0 or later.

**Comment by robertstarmer** [comment]
@taylor I'm not able to see the actual issue, but the fix appears to be in changing to a newer version of ansible in the tools container?

**Comment by taylor** [comment]
@robertstarmer https://github.com/cncf/cnfs/blob/master/comparison/ansible/roles/retr0h.etcd/requirements.txt#L1
