### ISSUE TITLE
Add shared service chain support to traffic generator setup

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#136]
## Add shared service chain support to traffic generator setup

- [ ] Reference diagrams in https://github.com/cncf/cnfs/issues/134

- [ ] Create 2 vlans for testing and share with team
- [x] Update nfvbench configuration to set `service_chain_shared_net=true`
- [ ] Update configuration to use test vlan ids
- [ ] Update vpp vswitch configuration to use vlans
- [ ] Minimal testing to ensure service chain sharing for vlans is working
- [ ] update multichain test case to use new configuration

After initial testing on quadtestb-01 to 04 is working:

- [ ] Update remaining ansible code for new configuration
- [ ] Update existing test machines to use new configuration

**Comment by taylor** [comment]
@pmikus 
> not relevant anymore.  new tickets will be opened for tasks that are required later.
