### ISSUE TITLE
Propose updates to naming conventions for repos and project slides

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#145]
Short description: 
- gathering ideas and references to make updates in CNF Project repos and slides

Examples:

Repos:
- [ ]  replace the word “Chained” with …

Slides:
- [ ]  slide 10 - change ‘Container NFs’ to be 'Cloud-native NFs' (to use consistent terminology throughout)
- [ ]  slides 8-11 - remove (VM) and (Pod) from slides
- [ ]  slide 11 - change ‘vswitch’ to ‘cswitch’ for CSC and CSP designs
- [ ]  slide 12 replace “Main Thread” with ...

**Comment by taylor** [comment]
@mackonstan, please propose changes in this issue with references to the standards you have mentioned.  Using terminology and classifications that are used by service providers which network functions (eg. telecos) is a good idea.

**Comment by taylor** [comment]
Closing until this topic is relevant again
