### ISSUE TITLE
Add support to optionally use OVS for the OpenStack vswitch

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#150]
To support different development paths and allow performance comparisons with and w/o VPP vswitch it would be useful to support alternative vswitch.

- [x] Add support to use an alternative to VPP neutron (eg. OVS or linuxbridge) in a new Ansible playbook
   * Copying the [openstack_chef_install](https://github.com/cncf/cnfs/blob/master/comparison/ansible/openstack_chef_install.yml) playbook and using a different role is fine
- [x]  Add option to use the non-vpp neutron option in the [openstack deploy script](https://github.com/cncf/cnfs/blob/master/tools/deploy_openstack_cluster.sh)
   * This could be an environment variable or cli option to the deploy_openstack_cluster script
- [x] Deploy cluster to Packet development and share access info with team

---

Additional items:

- [x]  VNC/Console is not properly configured
- [x]   Further network validation still needed
- [x]   Ubuntu unbond and vlan mapping function still needs to be incorporated
- [x]   VPP install should be added

Test:
- [x] Intranode VM to VM communication works as expected 
- [x] Node-to-Node VM communication works as expected
- [x] Openstack deployment to a new set of Packet on-demand instances works as expected

**Comment by robertstarmer** [comment]
Basic deployment on both CentOS and Ubuntu are alive.  There are still outstanding issues that can be addressed:
- [ ] VNC/Console is not properly configured
- [ ] Further network validation still needed

**Comment by taylor** [comment]
@robertstarmer Ubuntu items can be addressed in https://github.com/cncf/cnfs/issues/156

**Comment by robertstarmer** [comment]
OVS support works.  Router configuration still needs some documentation and can be automated against Packet.net's L3 services.

@taylor @denverwilliams
