### ISSUE TITLE
Create a network function design document for the snake and best case under docs

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#155]
Include diagrams for wiring, cpu core assignment, high-level diagrams for test cases

- [ ] Move wiring diagram from  into new document [comparison README](https://github.com/cncf/cnfs/blob/master/comparison/kubecon18-chained_nf_test/README.md)
- [ ] Add wiring diagram for K8s
- [ ] Logical diagrams See https://github.com/cncf/cnfs/issues/134#issuecomment-440061848
- [ ] Add network overview.  Eg. https://github.com/cncf/cnfs/issues/134#issuecomment-440754120
- [ ] Add diagrams / details for cpu core assignment
- [ ] Add diagrams going over network function service chains

**Comment by michaelspedersen** [comment]
### CPU Pinning for initial set of CNF benchmarks on K8s (Intel NIC) [Nov 30.]
![image](https://user-images.githubusercontent.com/40474606/49397466-e63ed580-f6f8-11e8-8b3d-fcadca8788ad.png)
- I'll put this here initially. We can update or align before using it for documentation
