### ISSUE TITLE
Update OpenStack Ubuntu host option to use Ubuntu 18.04 LTS (Bionic)

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#161]
Current OpenStack deploys using Ubuntu are on Xenial, 16.04.  To keep things in parity with the K8s host we need to add 18.04 support for the OpenStack host OS.

Tasks:
- [x] Chef openstack targets queens (latest available) and the Ubuntu Bionic OpenStack repo does not have Queens code, so we need to change the target the the Xenial repo.
- [x] Chef for Queens targets Python 3.5, Bionic has Python 3.6 and either the Chef code doesn't like a newer version (and needs a Chef config update to support it), or the Python version needs to be downgraded.
- [x] Update VPP-Neutron
   * [x] Update VPP-networking software to 18.07
   * [x] Update VPP software to 18.07
   * NOT required: Update DPDK

Additional items:
- [x] A python target code mismatch that appears hard-coded in the OpenStack chef codebase
- [x] A change in the name for the "targetcli" python library (becomes targetcli-fb)
- [x] Python version needs to become 3.6
- [x] I updated the ruby mysqld gem from 0.4.9 to 0.5.2 (this may have been spurious, but appears to cause no other issues)
- [x] A re-work of which repositories are used to get Ubuntu OpenStack queens code
- [x] A change in the mysql version from 10.0 to 10.1

Intel NIC support
   *  Intel supported in VPP+DPDK for VPP 18.07 and Ubuntu 18.04
   * [x] Basic intranode network connectivity VM to VM ping on the same compute node
     * This actually just talks from the VM through the VPP vswitch through vhost-user
   * [x] Basic internode network connectivity VM to VM ping on different compute nodes
     * [x] Deploy second compute node

Mellanox NIC support 
   * [x] Update Mellanox drivers to version for Ubuntu 18.04
       * [x] If needed, Update vpp dpdk source build to use new driver
   * [x] Basic intranode network connectivity VM to VM ping on the same compute node
  * [x] Basic internode network connectivity VM to VM ping on different compute nodes
     * [x] Deploy second compute node

**Comment by robertstarmer** [comment]
Current known issues:

- [ ] Chef openstack targets queens (latest available) and the Ubuntu Bionic OpenStack repo does not have Queens code, so we need to change the target the the Xenial repo.
- [ ] Chef for Queens targets Python 3.5, Bionic has Python 3.6 and either the Chef code doesn't like a newer version (and needs a Chef config update to support it), or the Python version needs to be downgraded.

**Comment by robertstarmer** [comment]
Most of the issues came from two sources:

1) A python target code mismatch that appears hard-coded in the OpenStack chef codebase
2) A change in the name for the "targetcli" python library (becomes targetcli-fb)
3) Python version needs to become 3.6
4) I updated the ruby mysqld gem from 0.4.9 to 0.5.2 (this may have been spurious, but appears to cause no other issues)
5) A re-work of which repositories are used to get Ubuntu OpenStack queens code
6) A change in the mysql version from 10.0 to 10.1

**Comment by robertstarmer** [comment]
I still need to document the update, but as of my latest test, Mellanox and Intel deployments both produce functioning OpenStack environments on Ubuntu 18.04 on packet.net. Still need to update the documentation to close out on this item, though the system is smart enough to check for PCI devices to determine if you have Mellanox or Intel devices (looking specifically 5e00 or 1a00 for Mel and Int PCI devices).

**Comment by denverwilliams** [comment]
@lixuna  @taylor @robertstarmer QA for Ubuntu 18.04

Openstack/Mellanox with Ubuntu 18.04
• Cluster deploy: Working
• VM deploy: Working
• Standard inter-vm/vlan networking: Working

Openstack/Intel with Ubuntu 18.04
• Cluster deploy: Working
• VM deploy: Working
• Standard inter-vm/vlan networking: Working
