### ISSUE TITLE
[MWC] EPIC: Create READMEs for high-level overview with links to various steps per environment

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#166]
EPIC: Create READMEs for high-level overview with links to various steps per environment
---

**Comment by taylor** [comment]
TODO: add flow charts for steps

**Comment by taylor** [comment]
WIP: Description of the OpenStack environment deployment stages:
---

What software runs to setup the CNF Testbed?

Steps:
1. User: Pre-req steps on workstation to run repo code (install docker, git, etc)
2. User: Clone https://github.com/cncf/cnf-testbed
3. User: Create configuration with Packet API, number of nodes, etc
4. User: runs deploy_openstack_cluster.sh
5. Docker deploy container starts and runs terraform
6. Terraform provisions either on-demand or reserved Packet instances via API
7. Terraform runs ansible via plugin running the openstack install role
8. Ansible openstack install role creates the Packet VLANs with a Packet API client
9. Ansible runs the Chef install role to start the Chef OpenStack install
10. Chef installs OpenStack
11. Ansible installs VPP on the compute nodes as the vSwitch for OpenStack

**Comment by taylor** [comment]
WIP: Description of the K8s environment deployment stages:

Steps:

1. User: Pre-req steps on workstation to run repo code (install docker, git, etc)
2. User: Clone https://github.com/cncf/cnf-testbed
3. User: Create configuration with Packet API, number of nodes, etc
4. User: runs deploy_k8s_cluster.sh
5. Docker deploy container starts and runs terraform
6. Terraform provisions either on-demand or reserved Packet instances via API
7. Terraform runs ansible via plugin running the k8s install role
8. Ansible k8s install role creates the Packet VLANs with a Packet API client
9. TBD

**Comment by taylor** [comment]
**Common Steps**
1. Clone https://github.com/cncf/cnf-testbed and install any pre-requites listed in the README
1. Create configuration with Packet API, number of nodes, etc ([k8s example](https://github.com/cncf/cnf-testbed/blob/master/tools/k8s_benchmark_quad_intel.env.example))
1. Run the ([k8s](https://github.com/cncf/cnf-testbed/blob/38a89ad2dde59711fda8015308a1f0b19f50e946/tools/deploy_k8s_cluster.sh) or [openstack](https://github.com/cncf/cnf-testbed/blob/38a89ad2dde59711fda8015308a1f0b19f50e946/tools/deploy_openstack_cluster.sh)) deploy cluster script which provisions the Packet machines with Terraform


**Openstack**

4. Terraform starts Ansible which pre-configures the Packet machines (using the openstack infrastructure playbook). The playbook configures the data plane interfaces, installs mellanox drivers, optimizes grub config and reboots the compute nodes
5. Ansible then runs the openstack install playbook, which configures the  Packet switch and VLANs and then deploys OpenStack using Chef to the Packet nodes
6. Ansible then installs & configures VPP as a vSwitch using the Openstack vpp-networking plugin to all compute nodes in the cluster
7. All OpenStack compute nodes are available for scheduling


**K8s**
- Cloud-init bootstraps the Kubernetes cluster on the Packet nodes. 
- The k8s vpp vswitch installer runs the Ansible k8s vpp vswitch playbook which configures the Packet switch and VLANs 
- Ansible then optimizes the system configuration, installs & configures the VPP vSwitch and reboots the worker nodes

**Comment by taylor** [comment]
![image](https://user-images.githubusercontent.com/26697/53061156-8566a400-3482-11e9-9e47-330df997f9f1.png)

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testbed/blob/master/docs/steps_to_deploy_testbed.mkd
