### ISSUE TITLE
[GitHub] Update directory structure for VNF-CNF Test Cases and READMEs

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#167]
Feature: Update directory structure for VNF-CNF Test Cases and READMEs
---

**Short Description:** 
- decide how to structure directories & documentation in GitHub
- will use a more general structure
- will help inform the READMEs to reproduce OpenStack and K8s environments
- set up a framework at top level
- add "events" under the top level 
  - ie. KubeCon specific tests, MWC specific tests

**Current Issues:** 
- files are listed under KubeCon NA 2018 
- tests are not at top-level, hard to find

**Potential Issues:** 
- tests may break, ie. Ansible
- an event-specific, one-button set-up+tests would need to go into a sub-folder per event, ie. MWC

Tasks: 
---

- [x] Decide = modify existing or start from scratch with new repo?
  - Decision: modify 

- [ ] Rename repo to cncf/cnftestbed 
   - goal of top level repo is "how to create a testbed"

**Comment by taylor** [comment]
Completed
