### ISSUE TITLE
IPv6 support for CNF/VNF

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#169]
## Adding IPv6 support to CNF/VNF
Goal is to have support for the following cases
- [x] Bare-metal
  - [x] CNF (CSP)
  - [x] CNF (CSC)
  - [x] VNF (VSC)
- [ ] K8s (Helm)
  - [ ] CNF (CSP)
  - [ ] CNF (CSC)
- [ ] Openstack
  - [ ] VNF (VSC)

### Bare-metal deployment
Currently supported as listed above. Deploy using the 'cnfdeploytools' container with the following command:

```
ansible-playbook install_network_functions.yml \
    -e tg=<Packet generator node> \
    -e sut=<System under test node> \
    -e sut_nic=<intel|mellanox> \
    -e deploy_env=<Deployment environment> \
    -e ipv6=<true|false> \
    -e facility=<Packet.net facility>
```

See #168 for info on setting up the Packet generator to support IPv6

### K8s deployment
TODO

### Openstack deployment
TODO

**Comment by michaelspedersen** [comment]
A few comments on b7cabb6:
* I had a weird bug with the previously used interfaces on the packet generator with Intel NICs (related to MAC addresses - No details collected). Solved by using different interfaces
* IP addresses used for IPv6 match the ones described in #168. Scripts will need to be updated if different addresses are to be used.
* With the VPP configuration for IPv6 in CNFs, memif interfaces would be in "down" state. Workaround is to set interfaces "up" after VPP has started, followed by continuously sleeping to keep container from exiting.
* Small error with assigning MACs for VNFs corrected.

**Comment by taylor** [comment]
- [x] The VPP NF code works for IPv6

Deferring creating use cases with IPv6
-  K8s (Helm)
    -  CNF (CSP)
    -  CNF (CSC)
-   Openstack
    -  VNF (VSC)
