### ISSUE TITLE
Implement chained VNF routers test case (aka "router snake test") on OpenStack 

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#175]
**Test Name: Chained VNF routers (aka "router snake test")** 

**Short Description:** 
- 1 or more network functions (NF) connected from one to the next through the vswitch
- The network traffic loops from the vswitch to the first NF then back to the vswitch and onto the next NF, ending at the vswitch (which can send traffic out of the node)

![image](https://user-images.githubusercontent.com/26697/53215061-a3640e00-3614-11e9-8aca-4a73f05c3de3.png)

**Audience:** 
- Teleco engineers
- NFV platform implementers

**Environment to support:** 
- OpenStack
- Packet.net on-demand instances

---
---

Tasks:
---

_Deploy router with public internet access_
- [x] Deploy new physical machine on Packet with Ubuntu
- [x] Configure system for public internet access - in-bound and outbound
- [x] Configure system to support NATing traffic from other systems on the same internal network
- [x] Test sending traffic through router from an OpenStack VM to the internet
- [x] Test SSH from the router to the VM
- [ ] Document router setup in [docs/standalone-router_setup.mkd](https://github.com/cncf/cnf-testbed/blob/master/docs/standalone-router_setup.mkd)

_VNF image creation_
* [x] Build a VNF router image
   - [x] Create a Ubuntu 18.04 VM based on the baseline nf performance [vEdge VNF](https://github.com/cncf/cnfs/tree/master/comparison/baseline_nf_performance-packet/vEdge) 
   - [x] Create a qcow-based image by creating a snapshot of the running VNF
* [x] Deploy a new VM using the VNF router image
   * [x] Verify SSH to the VM works as expected
* [x] Destroy the VM after testing
 
_OpenStack CLI deployment support_
- [x] Use cli to create tenant networks for test traffic
   * [x] tenant network 1 with 1st vlan
   * [x] tenant network 2 with 2nd vlan
- [x] Setup router to be on both VLANs which are used in OpenStack for it's tenant networks
- [x] Deploy VNFs using the VNF image attached to the two tenant networks

_HEAT deployment support_
* [ ] Implement/modify HEAT template to establish multiple tenant networks
* [ ] Implement/modify HEAT template to deploy test VMs attached to tenant networks
* [ ] Implement/modify HEAT template to allow VMs to connect to public internet

Requirements:
- Implementation must support both OVS and VPP based vswitches using a common OpenStack interface (eg. Neutron API from CLI or HEAT)

Acceptance Criteria:
---

pre-reqs: 
- User downloads this repo and sets up prereq software (eg. Docker)
- OpenStack cluster has been deployed with a working private tenant (test) network
   * Can use a OVS or VPP vswitch.

_Deploy a single VNF VPP-based ipv4 router to OpenStack_
1. When a user runs the deploy vnf router script with argument of 1
1. Then a single VM will be instantiated on OpenStack
1. And the VM will have an private IP address with a known VLAN
1. And the VM will be reachable by SSH and ping on it's private IP from another machine on the same VLAN

Results:
- [ ] Passes OVS OpenStack
- [x] Passes on VPP-neutron OpenStack

_Chained router test case with 1 or more VNFs and multiple interfaces_
1. When a user runs a script passing the number of VNFs that should be deployed for the chain
1. Then VMs will be deployed to OpenStack
1. And a virtual interface will be attached/created on the VM with a VLAN for inbound traffic
1. And a second virtual interface will be attached/created on the VM with a VLAN for outbound traffic
1. And Network connectivity will be established from the VPP vswitch to the first test virtual interface
1. And Network connectivity will be established from the VMs second test virtual interface
1. And the VM will have a 3rd network interface with routing to the public internet 
* And the VM will be reachable by SSH and ping on it's private VLAN interfaces from another machine on the same VLAN
* And the VM will be reachable on it's private VLAN interfaces by other VMs on the same node 
* And the VM will be reachable on it's private VLAN interfaces by other VMs on different nodes

Results:
- [ ] Passes OVS OpenStack
- [x] Passes on VPP-neutron OpenStack

_Outbound internet access from VNFs_
1. When a user runs a script passing the number of VNFs that should be deployed for the chain
1. Then VMs will be deployed to OpenStack
1. And the VM will have full Internet access
1. And HTTP requests to systems on the internet work as expected
1. And SSH to systems on the internet work as expected
1. And PING to systems on the internet work as expected

Results:
- [ ] Passes OVS OpenStack
- [x] Passes on VPP-neutron OpenStack

_Network traffic flows through the entire VNF chain to external destination_
1. Given the VNFs are running on OpenStack in the expected configuration
1. And a user is on a machine configured with the VLANs and IPs which are on the same network as the OpenStack compute nodes running the VNFs
1. When a user sends ICMP and ARP requests through the first VNF in the chain with a destination of a system outside of the chain which the final VNF can reach (eg. nfvbench VLAN2 interface)
1. Then the user should receive ICMP and ARP replies as expected

Results:
- [ ] ICMP Passes OVS OpenStack
- [x] ICMP Passes on VPP-neutron OpenStack
- [ ] ARP Passes OVS OpenStack
- [x] ARP Passes on VPP-neutron OpenStack

**Comment by taylor** [comment]
Referene https://github.com/cncf/cnfs/issues/173 for other details on public internet access being added to VPP-based OpenStack

**Comment by taylor** [comment]
@robertstarmer #181 will be a blocker for implementing this ticket

**Comment by taylor** [comment]
*Planning VNF setup on OpenStack*

VNFs currently 

Issues:
- NFVbench is currently configured to use the mac address of the ingress/egress of the VNF chain
- VPP in the VNF currently uses the mac addresses of other VNFs in the chain for routing traffic


Questions:
- Can we specify the mac address with VPP-neutron?  
   * Reference https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/port.html, https://docs.openstack.org/newton/user-guide/cli-create-and-manage-networks.html

/cc @denverwilliams @michaelspedersen

**Comment by taylor** [comment]
@denverwilliams new item added for documenting the router setup.

**Comment by robertstarmer** [comment]
@taylor, @denverwilliams  I did check, and at least with a pre-defined port:
openstack port create <port_name> --network <network_name> --mac-address <00:11:22:33:44:55>
I was able to launch a server:
openstack server create --nic port-id=<port_id> {rest of server create parameters}...

**Comment by taylor** [comment]
A/C moving out of this issue
---



_WIP: (NOT READY DRAFT ONLY) - Public in-bound internet access to VNFs in chained router test case_
1. When a user runs a script passing the number of VNFs that should be deployed for the chain
1. Then VMs will be deployed to OpenStack
1. And the VM will reachable on it's "public" interface over SSH and ping from the internet

Results:
- [ ] Passes OVS OpenStack
- [ ] Passes on VPP-neutron OpenStack

_ARP and ICMP reaches any VNF in the chain_
1. Given the VNFs are running on OpenStack in the expected configuration
1. And a user is on a machine configured with the VLANs and IPs which are on the same network as the OpenStack compute nodes running the VNFs
1. When a user sends ICMP and ARP requests through the first VNF in the chain with another VNF as the destination
1. Then the user should receive ICMP and ARP replies as expected

Results:
- [ ] ICMP Passes OVS OpenStack
- [ ] ICMP Passes on VPP-neutron OpenStack
- [ ] ARP Passes OVS OpenStack
- [ ] ARP Passes on VPP-neutron OpenStack

**Comment by taylor** [comment]
![image](https://user-images.githubusercontent.com/26697/52765046-1b647f80-2fe8-11e9-8020-1255b911cebe.png)

**Comment by taylor** [comment]
@denverwilliams / @robertstarmer please document how to create the network, port and instantiate the VM for OpenStack VPP (as it's not exactly what is expected).

**Comment by taylor** [comment]
Notice: API issues documented in https://github.com/cncf/cnf-testbed/issues/193 are severely slowing down completion of the VNF implementation and testing.

**Comment by taylor** [comment]
*Description of env:*
- Packet on-demand m2.xlarge with Mellanox ConnectX-4 NICs
- VPP 18.07
- OpenStack vpp-networking
- DPDK ?
- NASM ?

**Comment by robertstarmer** [comment]
DPDK: 18.05
NASM: 2.13.03 from OSU.

**Comment by taylor** [comment]
![image](https://user-images.githubusercontent.com/26697/52441152-922fe300-2ae5-11e9-80bd-ff14c3554aac.png)

**Comment by taylor** [comment]
Benchmark results for this test case (on Mellanox NIC Packet instances) is in #199

**Comment by taylor** [comment]
Defer *HEAT deployment updates* to another ticket

- [ ]   Implement/modify HEAT template to establish multiple tenant networks
- [ ]   Implement/modify HEAT template to deploy test VMs attached to tenant networks
- [ ]   Implement/modify HEAT template to allow VMs to connect to public internet

**Comment by taylor** [comment]
Defer: Document router setup in docs/standalone-router_setup.mkd
