### ISSUE TITLE
[Documentation] Block diagram Components on Bare Metal + software to provision OpenStack, 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#179]
- [x] Software components running in testbed for openstack environment
- [x]diagram deployment steps for testbed

- [x] table with steps

----

![image](https://user-images.githubusercontent.com/26697/53590774-2971de80-3b58-11e9-96de-d4297b9d47e8.png)

**Comment by Sai-Adarsh** [comment]
@lixuna I'm interested, could you guide me through with some more pointers on what to contribute?
