### ISSUE TITLE
[Documentation] Block diagram for Steps to install OpenStack clusters

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#180]

**Comment by taylor** [comment]
See #166 for written steps

**Comment by wavell** [comment]
![image](https://user-images.githubusercontent.com/29548/52785873-bd9f5a00-301e-11e9-8906-c8a4c65712c2.png)
![image](https://user-images.githubusercontent.com/29548/52785949-07884000-301f-11e9-8199-df0528569a12.png)

**Comment by taylor** [comment]
![image](https://user-images.githubusercontent.com/26697/53587685-971a0c80-3b50-11e9-8f47-993815d407c1.png)

**Comment by lixuna** [comment]
steps were documented in a table per request - see above. closing as complete.
