### ISSUE TITLE
[OpenStack] vpp-agent crashes when it tries to attach multiple tenant networks/interfaces to the vm

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#181]
Problem: vpp-agent crashes when it tries to attach the ports to the vm

**Short Description:**

* We seem to be running into an issue with vpp when deploying a vm with more than one interface. 
* The vpp-agent successfully manages to create the ports, but it crashes when it tries to attach them to the vm.

`openstack  server create test${1} --flavor ${FLAVOR} --key-name oskey --image xenial --nic net-id=7fef025c-8d0e-4fd7-82f0-45f6d3cbb9dd --nic net-id=a3fadec9-a4c8-4ee2-a3a0-b88c6576af77  --config-drive True --user-data /tmp/test${1}.cfg`

**Reported by: @denverwilliams**  

**Environment to support:**

* OpenStack
* Packet.net on-demand instances

Tasks: 
---

- [ ] 

Acceptance Criteria: 
---

- [ ]

**Comment by denverwilliams** [comment]
@robertstarmer 
Something else that may help with debugging, is that we were never able to deploy another vm from the point that vpp crashed, even after a full restart of neutron/vpp on the controller/compute nodes. - vpp was behaving in a way similar to when we were have trouble with the numa zones/hugepages, so i suspect it may be related to that.

**Comment by robertstarmer** [comment]
With a VPP environment with VMs deployed and working with a single interface, it appears that one can attach a second interface using the "openstack server add port <server> <port>", and then manually associate an IP and bring the interface up.

openstack port create <port_name> --network <network_name>
openstack server add port <server_name> <port_name>

Log into server (I did manually via console: openstack console url show <server_name>)
become root
```sudo su -```
{wait for DNS timeout}
ip link set up dev ens6
ip address add {port_address/port_netmask from openstack port list} dev ens6

**Comment by taylor** [comment]
ONAP demo for the vCPE use case has heat templates with multiple interfaces.  They create neutron ports then use nova server to attach the ports to the server https://github.com/onap/demo/blob/master/heat/vCPE/vgmux/base_vcpe_vgmux.yaml#L171

**Comment by robertstarmer** [comment]
- [ ] Need to test based on the HEAT model (e.g. pre-create ports, and then associate ports on server create).

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testbed/issues/175#issuecomment-463025228

**Comment by taylor** [comment]
@robertstarmer is this issue ready to close?

**Comment by robertstarmer** [comment]
@taylor yes, I believe this was all due to a difference in interaction with etcd2 vs. etcd3.
