### ISSUE TITLE
Create an ansible playbook and terraform code for deploying a outbound router to Packet

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#185]
Goal: Provide public outbound internet access for the OpenStack VPP clusters
---

As part of implementing the VNF snake test case in #175 a router was manually deployed on a Packet instance.  Until routed networking for public internet access is working as expected having an automated solution for deploying a external router is desired.

Terraform can be used to create a Packet machine to deploy a router to.

The ansible code should support deploying to a Packet machine or a VM if that's desired later.

Tasks:
- [ ] Create terraform code to provision a small packet instance
   * Should work with existing terraform cluster deploy code
   * optionally: works stand-alone to deploy a router to be used in an existing cluster or independently
- [ ] Create a ansible playbook for deploying a linux router as documented [docs/standalone-router_setup.mkd](https://github.com/cncf/cnf-testbed/blob/master/docs/standalone-router_setup.mkd) and #175 
- [ ] Update openstack install code to use new router role on deploys

**Comment by taylor** [comment]
@michaelspedersen, how is this done from a VM/chain side in openstack.

@denverwilliams: router is given an IP tagged with the same VLAN used in the tenant network.  Then create the network with default route to the router.

**Comment by robertstarmer** [comment]
With the fix pointed out by Ian Wells (resolved in a newer version of the networking-vpp codebase). The issue was a Unicode translation mismatch in passing IP Addresses.  The current master testbed code has a fix for this issue, and Neutron Router now works properly.
@taylor @denverwilliams

**Comment by taylor** [comment]
See #204 for using the router inside of OpenStack

**Comment by taylor** [comment]
INVALID

Openstack routing now works
