### ISSUE TITLE
[Documentation] What is the chained IP router snake test case?

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#186]
Why is this test case important?

What is the test case?

**Comment by taylor** [comment]
WIP Draft: Explain the chained ip router snake test case
---

*Why is this test case important?*
- Determine maximum performance, in packets per second, of data plane throughput 
- Provides stress testing of NFV infrastructure, particularly the vSwitch
- Easier verification by reducing layers of complexity
- Building block for more complex test cases

This test case provides an easily verifiable test for comparing the highest throughput achieved without dropping packets (also called NDR) when forwarding data plane traffic in each environment (eg. K8s and OpenStack) through the network functions.

Router performance is often associated with its forwarding capabilities which will be affected by poor performance in the data plane.

*What is the test case?*
A single, simple, VPP-based IP router is used as the network function (NF) for this test case.  This network function does IPv4 and IPv6 packet forwarding.

VPP is used as the host data plane vswitch for all environments (eg. OpenStack and K8s).

The network functions are deployed in a series with one NF connected to the next into the test environment (eg. OpenStack or K8s). The number of connected NFs, eg. 2-8, deployed is configurable.

In the snake test case, the network interfaces for data plane traffic are all connected to the vswitch for both OpenStack and K8s environments.  All packets destined for a network function will go through the vswitch which forwards the packets to the network function.  Like-wise all packets leaving a network function will go into the vswitch before being forwarded to the next destination, which could be the next network function in the chain.

In the OpenStack environment a vhost-user virtual network interface is used to connect the VNF with the vswitch.  For the K8s environment a Shared Memory Packet Interface (memif) is used to connect the CNF with the vswitch.

**Comment by taylor** [comment]
Version with images

**What is the test case?**
This test case provides a configuration where all data plane traffic will flow from the vswitch into the first network function, back to the vswitch and onto the next network function until it has looped or snaked through every network function in the chain.

Let's break that down:
A single, simple, VPP-based IP router is used as the network function (NF) for this test case. This network function does IPv4 and IPv6 packet forwarding.

![image](https://user-images.githubusercontent.com/26697/52740964-e5001380-2f99-11e9-897a-655df7d01f3f.png)

[VPP](https://wiki.fd.io/view/VPP/What_is_VPP%3F) is used as the host data plane vswitch for all environments (eg. OpenStack and K8s).

The network functions are deployed in a series with one NF connected to the next into the test environment (eg. OpenStack or K8s). The number of connected NFs, eg. 2-8, deployed is configurable.

![image](https://user-images.githubusercontent.com/26697/52740742-54c1ce80-2f99-11e9-95b7-0afc5e9fe036.png)

In the snake test case, the network interfaces for data plane traffic are all connected to the vswitch for both OpenStack and K8s environments. All packets destined for a network function will go through the vswitch which forwards the packets to the network function. Like-wise all packets leaving a network function will go into the vswitch before being forwarded to the next destination, which could be the next network function in the chain.

![image](https://user-images.githubusercontent.com/26697/52741493-11685f80-2f9b-11e9-869d-388f2a79ae3e.png)


In the OpenStack environment a vhost-user virtual network interface is used to connect the VNF with the vswitch. For the K8s environment a Shared Memory Packet Interface (memif) is used to connect the CNF with the vswitch.


[TBD Visual for vhost-user vs memif]

**Comment by lixuna** [comment]
close as complete - see above write up and images.
