### ISSUE TITLE
BUG: Openstack API timeouts (mainly on port actions)

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#193]
When creating, viewing or deleting ports, the following error often occurs:
```
HttpException: 500: Server Error for url: http://147.75.70.41:9696/v2.0/ports, Request Failed: internal server error while processing your request.
```

Following the first error the connection seems to remain sporadic for a couple of minutes. 

Seen on the VPP1 instance (Openstack with Mellanox NICs)

**Comment by robertstarmer** [comment]
I restarted apache2 on vpp1, and the port list is returning empty. I'm not
seeing anything obvious in the logs that would have caused the API to
become non-responsive though.

**Comment by taylor** [comment]
Michael Pedersen [4:20 AM]
>>>@rstarmer Looks like it is still occurring
HttpException: 500: Server Error for url: http://147.75.70.41:9696/v2.0/ports/2_3_3_l, The server has either erred or is incapable of performing the requested operation.: 500 Internal Server Error

and

HttpException: 500: Server Error for url: http://147.75.70.41:9696/v2.0/ports, Request Failed: internal server error while processing your request.

**Comment by taylor** [comment]
@robertstarmer @michaelspedersen  tried omitting the external ports/interfaces and adding delays between calls with out any success.  It's very time consuming

**Comment by robertstarmer** [comment]
It appears that the instability was principally driven by the mysql service not only closing "idle" connections (this still appears in the log, even with a greater number of max_connections defined) but not having enough connections in the pool available.

Increasing the max_connections parameter in /etc/mysql/conf.d/openstack.cnf from the default of 307 to 1451 (a random much larger number) appears to have resolved the issue.  Further tuning would be appropriate to avoid wasting memory on the control node(s).

@michaelspedersen @denverwilliams @taylor @robertstarmer @bvera

**Comment by michaelspedersen** [comment]
Thanks @robertstarmer 
After applying this fix the API seems completely stable.

Closing ticket
