### ISSUE TITLE
Add test example that uses K8s CPU POD restricted access

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#194]
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#cpu-management-policies

Also review Intel cpu  pinning tools

Tasks:
- [ ] Review [CPU Manager for K8s](https://github.com/intel/CPU-Manager-for-Kubernetes)
- [ ] Create example that can toggle the use of the CPU manager
- [ ] Compare the results with CPU manager turned on vs off

**Comment by michaelspedersen** [comment]
Closing this issue, as CPU Manager is available in CNF Testbed. We can create a new ticket for testing if needed
