### ISSUE TITLE
BUG: vpp-networking appears unstable with port-security

### ISSUE THREAD

**Issue by robertstarmer** [cncf/cnf-testbed#198]
The default for a new network is to include port security (e.g. security groups) on a new port associated with a network.  This appears to create instabilities with the currently functional VPP deployment model.  Disabling port-security at network create time appears to address this, although the default "firewall" service for the ports is supposed to be a no-op.  There may be an issue either with the neutron configuration parameter or with the vpp-networking code's rendering of the configuration parameter.

**Comment by taylor** [comment]
This was found while working on API timeout issues in https://github.com/cncf/cnf-testbed/issues/193

**Comment by taylor** [comment]
Until needed we will leave port security disabled.  There are other options to achieve the same results.
