### ISSUE TITLE
Implement 'public' out-bound access from VNFs to the Internet on OpenStack-VPP

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#204]
Feature: add support for public outbound internet access from the vms
--- 

Tasks:
---
- [x] Document OpenStack router create script for local access with VPP
- [x] Update OpenStack deployment code to enable masquerading on the compute nodes

Acceptance criteria:
---

_VM deployed to VPP-neutron based OpenStack has external connectivity_
1. When a user instantiates a new VM on OpenStack
2. Then the VM will have an private IP address with a known VLAN
3. And the VM will be able to reach systems on the internet with TCP/IP and ICMP

Note: Internal networking will continue to work as expected

**Comment by robertstarmer** [comment]
Create a network with a gateway enabled (note that by default, for VNF cases, it is likely desireable to not enable a gateway '--gateway none' as a part of a CLI network create):

```shell
/root/create_gatweay_nw.sh {external_net_vlan_id}
```
This script will:
- create a vlan network called 'vlan{external_net_vlan_id}' on provider segment {external_net_vlan_id} which should be associated with the default "provider" Neutron interface type
- create an L3 subnet called 'subnet{external_net_vlan_id}' with a randomized IP address range of the form: 10.Y.X.0/24 where Y and X are a random value between 0 and 254.
- allocate the '.1' address (10.Y.X.1) to the router gateway
- establish DNS pointing to 8.8.8.8 and 8.8.4.4
- create a public side interface on the control node (where the script is run) allocated to the "uplink" VPP loopback interface with an IP address of 10.255.255.1/24 and update the local network configuration for the uplink with this information
- bring 'up' the uplink interface
- enable IP routing on the control kernel to support IP Masquerading
- enable IP Masquerading against the bond0 interface to support Upstream (from aVM to the Internet) NAT translated communication.

**Comment by robertstarmer** [comment]
There is now a ```/root/create_masq.sh``` script that takes at least one parameter: ```vlan_id``` and can also take a network, CIDR, and gateway address.  This will associate the ```vlan_id``` network (which it will try to create) with a VPP-router instance and a `netext` network that is stubbed out on the single controller node.  That network is given a default network of 10.20.30.0/24, which can be overridden, and if a Packet.net L3 network is associated with the ```uplink``` interface and the network information is provided as a part of the deployment, then the system (gateway address still needs to be CIDR subnet[0] address +1) will allow for Floating IP addresses as well.
