### ISSUE TITLE
VPP vSwitch in a POD for K8s w/Intel NICs

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#205]
Feature: Add support for running the (VPP) vSwitch in a POD for K8s for Intel NICs
--- 

Requirements:
- Continue to support running the vSwitch in the host as an option for k8s cluster provisioning
- Optionally choose to run the vSwitch in a container / POD

Tasks:
---
- [x] Create Dockerfile for building VPP vSwitch in a container (similar to the host build)
- [x] Create Helm chart for deploying VPP vSwitch as a container (similar to the host build)
- [x] Enable hyper-threading on status-worker-1.status.packet.local
- [x] Add basic dev documentation/notes to the [vpp vswitch README](https://github.com/cncf/cnf-testbed/blob/master/comparison/baseline_nf_performance-packet/host_vpp_container/README.md)

_Deploy tasks_
- [x] (TBD) Update https://github.com/cncf/cnf-testbed/blob/master/tools/deploy_k8s_vppvswitch.sh

_Intel support_
   * no drivers needed
- [x] Test on reserved instances with Intel x710 quad ports (Docker)
- [x] Test A/C on reserved instances with Intel x710 quad ports (Helm)
   - [x] _3 chain 2 node Pipeline on a K8s cluster with a POD-based vSwitch_
   - [x] _3 chain 2 node Snake testcase on a K8s cluster with a POD-based vSwitch_

Acceptance criteria:
---

_3 chain 2 node Pipeline on a K8s cluster with a POD-based vSwitch_
1. Given a user runs the deploy k8s script and specifies using a POD based vswitch
2. And the a K8s cluster is deployed
3. And the vSwitch is deployed to the cluster with Helm
4. When we deploy the 3 chain, 2 node pipeline test case
5. And the user runs nfvbench 
6. Then the test should run successfully returning benchmark results for the entire chain

_3 chain 2 node Snake testcase on a K8s cluster with a POD-based vSwitch_
1. Given a user runs the deploy k8s script and specifies using a POD based vswitch
2. And the a K8s cluster is deployed
3. And the vSwitch is deployed to the cluster with Helm
4. When we deploy the 3 chain, 2 node snake test case
5. And the user runs nfvbench 
6. Then the test should run successfully returning benchmark results for the entire chain

**Comment by michaelspedersen** [comment]
Helm chart has been updating and now runs on our Intel k8s node. Functionality/performance still needs to be tested, but NIC ports are available and memifs created.

**Comment by taylor** [comment]
VPP container published to dockerhub https://github.com/cncf/cnf-testbed/blob/a73eeafbf1eb2fe6f311fe259dc3ff129cb49c97/comparison/baseline_nf_performance-packet/host_vpp_container/helm/VPPcontainer/values.yaml#L8

**Comment by taylor** [comment]
Moving Mellanox support to a new ticket

_Mellanox support tasks_
- [ ] Research moving OFED from the container to the host
   * DPDK may require some type of driver in the container
   - [ ] Possibly with a smaller subset in the container

**Comment by michaelspedersen** [comment]
Debug note:
* If k8s doesn't come up after reboot, disable swap

**Comment by michaelspedersen** [comment]
Steps to deploy can be found in [Deploy_K8s_CNF_Testbed](https://github.com/cncf/cnf-testbed/blob/master/docs/Deploy_K8s_CNF_Testbed.md#deploy-k8s-cluster). The POD based vSwitch has been verified, and no difference is observed between running in the host (as a service) or in a privileged container,
