### ISSUE TITLE
Add unprivileged CNF IP Router Pipeline and Snake test cases without CPU core isolation

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#206]
Feature: Add unprivileged CNF IP Router Pipeline and Snake test cases
--- 

## Description:

Currently the test cases run the CNFs in a privileged mode where the software can see all CPU cores.  Ideally all CNFs will be unprivileged and see only the CPU cores which are assigned to them.

---

Requirements:
- Continue to support running privileged CNF test cases
- Optionally choose to run CNFs unprivileged 

Not in Scope:
- CPU core isolation
- NUMA zone isolation

Tasks:
---
- [ ] Update deployment script to optionally not pass privileged flag
- [ ] Update container to find available CPU

Acceptance criteria:
---

_3 chain 2 node Pipeline on a VPP+K8s cluster_
1. Given a VPP-based K8s cluster is deployed
2. When we deploy the 3 chain, 3 node pipeline test case unprivileged mode
3. And the user runs nfvbench 
4. Then the test should run successfully returning benchmark results for the entire chain

Expectation: The packets go through the chain and return to nfvbench.

_3 chain 2 node Pipeline on a VPP+K8s cluster_
1. Given a VPP-based K8s cluster is deployed
2. When we deploy the 3 chain, 3 node snake test case unprivileged mode
3. And the user runs nfvbench 
4. Then the test should run successfully returning benchmark results for the entire chain

**Comment by taylor** [comment]
@michaelspedersen said:

Intel has a plugin which is suppose to provide CPU exclusive access.  It can assign a set of cores to a container.

It does not allow specific threads to be assigned.

It would need to be updated to provide the specific pinning which we use in the performance test cases.

**Comment by michaelspedersen** [comment]
Commit https://github.com/cncf/cnf-testbed/commit/f1b941aabf6e8ecfdef94a620dff4012226c7b11 allows running CNFs without using the `--privileged` flag in Docker.

All cores are still visible in the container, but with correct CPU pinning done in the VPP configuration inside the container everything seems to be working.

I did notice a potential issue with this solution, as the performance of a 3 chains of 2 nodes configuration is noticeably lower when running without the privileged flag:
**MMR test (10Gbps load):**
* Privileged: 9,227,085 pps (6.2006 Gbps)
* Non-privileged: 7,598,550 pps (5.1062 Gbps)

Looking at the core utilization in the host (using `htop`) it looks like CPU allocation is correct in both cases. The consistent difference in throughput does however indicate that there is something happening, which I suspect is related to CPU allocation and/or scheduling.

**Comment by michaelspedersen** [comment]
Support for unprivileged CNFs added in 1ffb851ff71c511fa7cee3f6fd9a44575b7861d9
