### ISSUE TITLE
Update OpenStack documentation for Operating System selection

### ISSUE THREAD

**Issue by robertstarmer** [cncf/cnf-testbed#210]
The example OpenStack environment file needs to be updated to include Operating System selection, among other variables.

Acceptance criteria:

- [x] Known Operating Systems are listed and commented out
- [x] The variables defined have some basic description in the in-file comments

**Comment by linkous8** [comment]
Updated example depends on changes in #227 . Will submit a PR for this when that one is merged

**Comment by linkous8** [comment]
Updated documentation has been merged here https://github.com/cncf/cnf-testbed/commit/89fe35325da30120c3e629561fe1d1297482d3b1#diff-3780df677b1a6fca5eb6bb30f4cc3340
