### ISSUE TITLE
Associate VLAN ids with facility in Packet API client

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#219]
Feature: Associate VLAN ids with facility in Packet API client
---

**Short Description:**

- Packet VLAN IDs are unique only in a facility but can be duplicate between facilities.  
- The API client does not associate the VLAN ID with a specific facility so this causes various problems including false positives on duplicate VLAN ids.
- We'd like to associate VLAN ids with facility in Packet API client

Planning Tasks: 
---

- [ ]  Outline the plan for adding support to the Ruby client

- [ ]  Identify implementation tasks 

- [ ]  Estimate level of effort

- [ ]  Document Acceptance Criteria (how this will be tested)

- [ ] Create pull request to master
  * tag taylor and watson as reviewers

Test
---

_OpenStack_
- [ ] Deploy OpenStack with 2 compute nodes
- [ ] Deploy 1 VM to each compute node on same VLAN/tenant network
- [ ] Test network connectivity between the VMs

_K8s_
- [ ] Deploy k8s to Packet with OnDemand instances

_Secondary K8s tests_
- [ ] Create minimal POD/container deploy test
- [ ] Deploy POD to K8s cluster
- [ ]

**Comment by linkous8** [comment]
Fastest way to implement this would be to update the main.yml task of the packet_l2 role to incorporate facility into vlan name much like it already does for deploy_env

```
- name: Create or find a Packet VLAN
  command: ruby /packet_api/l2_packet_networking.rb --create-vlan="{{ facility }}{{ deploy_env }}{{ item.key }}" --project-name="{{ project_name }}" --packet-url='api.packet.net' --facility="{{ facility }}"
  with_dict: "{{ vlans }}"
  register: vlandata
```

This solution requires a few minutes worth of effort. 

It can be tested by validating in the packet layer 2 UI that the generated vlan descriptions are being named as desired.

Does this address the task items adequately or are there more things I should be considering?

**Comment by taylor** [comment]
@linkous8 this could be a short term fix but will not match existing VLANs. For a long term fix the ruby client needs to be updated to be aware of the facility association with the VLANs.

**Comment by linkous8** [comment]
In that case it would be better to update the create_vlan option of l2_packet_networking.rb in the packet_api container folder to check the facility when it compares pre-existing vlans. 

Effort should be about 2 hours (if you include waiting for the deployment to finish)

To test this, I would run a deployment with pre-existing vlan names but against a facility that did not contain said vlans and verify new vlans are generated with the same description in a new facility. Only roadblock to testing this is that we are already at the max of 12 virtual networks on packet so I would need to delete 2 of the existing vlans so new ones could be created. If someone could point me to two vlan instances that are not in use and safe to delete, I could do so.

**Comment by linkous8** [comment]
Update: project with vlan space has been identified. Will test updated ruby client later today

**Comment by linkous8** [comment]
I've updated and tested the packet api client. Please see branch https://github.com/cncf/cnf-testbed/tree/%23219-Feature-Associate-VLAN-ids-with-facility-in-Packet-API-client

**Comment by linkous8** [comment]
Fixed by: https://github.com/cncf/cnf-testbed/commit/2a607aaa569f8dc99b2ca2e2da093c363f2bfaf0

Specifically the changes to l2_packet_networking.rb
