### ISSUE TITLE
TBD - Add CentOS 7.6 support to OpenStack VPP cluster

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#221]
Tasks:
- [ ] Update chef meta data config
- [ ] Upate Ansible to support CentOS
- [ ] Update Ansible to install VPP 19.0.1.1
   * Mellanox enabled for CentOS package

**Comment by taylor** [comment]
Thomas Herbert
>This bug adds vpp 19.01.1 to Centos distro: https://bugs.centos.org/view.php?id=15989

**Comment by linkous8** [comment]
Additional update needed:
[ ] Update vpp_src_install to support CentOS

**Comment by linkous8** [comment]
Openstack (chef packages) appear to be migrating to here: https://opendev.org/openstack/openstack-chef

**Comment by linkous8** [comment]
work is on branch https://github.com/cncf/cnf-testbed/tree/feature-openstack-centos

Update: running into an issue with the version of epel-release being installed via ansible. I've directed ansible yum to a url (https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm) for an updated version but it doesn't seem to get installed (whereas running yum commands manually successfully downloads and installs it). That said, the dependencies and issues are for the vpp source build so I will make sure to attempt running the deploy on reserved intel instances within the next few days

**Comment by linkous8** [comment]
Update: centos does not seem available on reserved instances. Will reach out to packet support for ETA and continue with Mellanox hosts in the meantime

**Comment by linkous8** [comment]
Update RE Centos on n2 hosts: Support says Centos port is in progress and gave a best case scenario ETA of end of month

https://support.packet.com/tickets/RIBB-6739-ULCB

**Comment by linkous8** [comment]
Centos 7.6 can now be provisioned onto n2 hosts without issue
