### ISSUE TITLE
Onboard Thomas Herbert, RedHat to CNF Testbed

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#223]
Action item: Onboard Thomas Herbert, RedHat to CNF Testbed
---

Tasks:
---
- [x]  add T.Herbert to https://github.com/cncf/cnf-testbed

- [x]  ask T.Herbert to join cloud-native.slack.com
- [x]  T.Herbert join #cnf channel on slack
- [x]  T.Herbert join #nsm channel on slack

- [x]  Add T.Herbert to CNCF CNFs Packet project
- [x]  Add T.Herbert to CNF Sandbox Packet project
- [x]  T.Herbert Create personal Packet API key for deploying the clusters
- [x]  T.Herbert accept invites from Packet emails

**Comment by lixuna** [comment]
GitHub invite has been sent to @tfherbert > see https://github.com/cncf/cnf-testbed/invitations

<img width="724" alt="Screenshot 2019-04-12 16 11 23" src="https://user-images.githubusercontent.com/11701267/56066589-da65be80-5d3d-11e9-87f0-44a1cbd4760e.png">

**Comment by lixuna** [comment]
Email with instructions to join cloud-native.slack.com has been sent

**Comment by tfherbert** [comment]
I'm in.

**Comment by lixuna** [comment]
@tfherbert - please check your redhat email inbox for the Packet environment invites.
