### ISSUE TITLE
Add NSM packet-filtering example

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#242]
Support the NSM packet filtering example - https://github.com/networkservicemesh/examples/tree/master/examples/packet-filtering#universal-cnf-based-packet-filtering

**Comment by michaelspedersen** [comment]
The example has been added (using snapshot of NSM and NSM-example code as discussed with Nikolay).

The playbook can be found [here](https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/deploy_nsm.yml) and the documentation to support it is [here](https://github.com/cncf/cnf-testbed/blob/master/docs/Deploy_K8s_CNF_Testbed.md#run-nsm-packet-filtering-example)

**Comment by michaelspedersen** [comment]
Example is available through the [deploy_nsm.yml](https://github.com/cncf/cnf-testbed/blob/master/comparison/ansible/deploy_nsm.yml) playbook.
Connectivity out of the CNF chain is not yet possible. A new ticket can be opened for this once relevant.

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testbed/commit/21558f3ecbe2d758b8ac3acf71d6de6c793333f1
