### ISSUE TITLE
Add NSM example: Gateway + IP Router service chain

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#249]
A new example use-case is to be added to CNF Testbed. This use-case will include a single chain consisting of two `Gateway` endpoints, each with external access through a PF/VF, and two `IP routers` chained between the `Gateways`. An illustration of the use-case example can be seen below:
![nsm_ip_gw_chain](https://user-images.githubusercontent.com/40474606/63591795-19d7cd80-c5b0-11e9-9098-0371033a8d72.PNG)

This example requires external connectivity in the `Gateway` service using PF/VF interfaces, which is already tracked in https://github.com/cncf/cnf-testbed/issues/248.

Steps to implement:
- [ ] `Gateway` (Universal CNF) updated to support PF/VF (https://github.com/cncf/cnf-testbed/issues/248)
- [ ] Updated configuration for `Gateway` and `IP Router` services
  - `IP Router` must route/forward traffic between interfaces, according to the configuration of the external traffic source (e.g. NFVbench "packet generator")
- [ ] Test connectivity through chain using external server
  - Ping and/or UDP traffic
- [ ] Create configuration files for all services needed
- [ ] Create documentation for deploying and testing implementation

**Comment by nickolaev** [comment]
The example was merged with:
https://github.com/networkservicemesh/examples/pull/41

and is now available here:
https://github.com/networkservicemesh/examples/tree/master/examples/gw-routers
