### ISSUE TITLE
Observations and potential issues with Packet

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnf-testbed#251]
A list of observations with Packet. Listed here for visibility and reference.

### Servers fail to provision
Sometimes servers will fail to provision, resulting in the server not showing up in the Packet web portal, and an email being sent out to the person who provisioned it (based on API key and email address used).

This has been seen with different server types, e.g. m2.xlarge.x86 and t1.small.x86. It usually happens within smaller periods of time, which could mean that the server is added back to the pool, and if it is picked again during the following provisioning it is likely to fail again.

### Servers can't be switched to "Mixed networking
> With an n2.xlarge (Intel NIC) machine deployed in the SJC1 facility, I am unable to switch the network type from "Layer 3" to "Mixed/Hybrid". The error returned from the API states:
> `This device is not enabled for Layer 2. Please contact support for more details.`
> Trying to switch type on the web portal (app.packet) results in a similar error.
> 
> Steps to reproduce:
> Deploy n2.xlarge server in SJC1 facility
> Once available, switch network type from "Layer 3" to "Mixed/Hybrid"

A ticket was created with Packet on 7/10/19, and their networking team was looking into the issue. Similar issues were observed mid-august, and it seems like it only happens on **n2.xlarge (Intel NIC) servers**

### Ubuntu 18.04 LTS: Downloading packets with `apt` can cause timeouts
For a few periods during August, deployments have failed due to timeouts caused by slow download speeds with `apt`. 

When this issue has been observed, download speeds down to less than 1kbps have been seen. Checking the connection using "speedtest" tools show no problems with the connections. While the download speeds were low, several `apt` mirrors were tested with no difference in speed.

This **might** be an issue with the Packet infrastructure, and if it is observed again a ticket should be made to Packet containing relevant details.

**Comment by dankohn** [comment]
Cc @vielmetti

**Comment by vielmetti** [comment]
Thanks @michaelspedersen @dankohn . You can also reach out to me via email for any details on these, ed@packet.com .

The "failure to provision" issue can have a few different root causes. If you suspect that a machine type or a particular piece of hardware is failing repeatedly please let us know to investigate.

I'm looking at the SJC1 n2.xlarge ticket which is showing as "resolved". If that problem reoccurs currently, or shows up again in the future, please let us know. 

The slow `apt` speed is sometimes reported by other Ubuntu users around the net, with reports on Ubuntu forums dating back to 2011. One piece of common folklore includes references to slow speeds on IPv6 networks. If you hit this again, please test specific to IPv6.

**Comment by michaelspedersen** [comment]
Thanks for the update @vielmetti.

I'll try to keep track of the machines failing to provision (you probably have access to more details on each of the incidents).

I have not seen the issue with changing network type since I filed the ticket, and from there it looked resolved to me. I think @ckoester2 saw something similar a week or two ago, which I why I brought it up again in the list. We will keep an eye out for it, and check in with you or file a ticket as needed.

For `apt`, I was looking into it as well, and found similar information about IPv6. I tried a few of the workarounds to disable it, and from what I could see it was using IPv4 while the slow speeds were observed. Similar to the above, we will be sure to let you know if it is seen again, and hopefully you will have a chance to look at it before it corrects itself (usually within a day).

**Comment by dankohn** [comment]
I understand things are still very much in flux, but wouldn't best practice be to build your Ubuntu containers separately and then save them as immutable? The problem with running `apt` on the server is that every instance becomes a snowflake. The side effect might be sidestepping this bug.

**Comment by michaelspedersen** [comment]
@dankohn That would definitely be the best practice overall, and for most/all containers that are used as part of use-cases (service chains) this is already done.

We still support running the host vSwitch (VPP) directly on the host, and with m2.xlarge this requires building VPP from source using flags to include support the Mellanox ConnectX-4 NIC. There is also a handful of dependencies related to installing the workload infrastructure (K8s, Openstack) where `apt` is needed.

It is definitely something to keep in mind going forward, but regardless of our issues I still think it is relevant for Ed and Packet to figure out when and why this is happening, as it could, and likely would, affect other deployments too.

**Comment by michaelspedersen** [comment]
Closing as this has not occurred again for several months
