### ISSUE TITLE
Add Intel hardware NIC assignment to the GW 

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#258]
- [x] Push configuration with helm to assign NIC

**Comment by michaelspedersen** [comment]
Current implementation can be found in https://github.com/cncf/cnf-testbed/tree/wip-new-examples-structure/examples/use_case/external-packet-filtering-on-k8s-nsm-on-packet, with the README specifying (almost*) all the steps needed to deploy

*) Only tested on Kubernetes cluster deployed with host vSwitch (VPP). Following the additional steps posted in the README it should be possible to mimic the same configuration by hand
