### ISSUE TITLE
Upload CNF Testbed logos to /artwork folder

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#273]
**Feature Name:** 

- Upload CNF Testbed logos to /artwork folder

**Short Description:** 
-  update logos per Horizontal, icon, stacked for different color options
- save files using the convention used for CNCF projects, for example networkservicemesh-horizontal-color.png,  `[project-name]-[orientation]-[color/black/white].[png/svg]` as seen in https://github.com/cncf/artwork/tree/master/projects/networkservicemesh

**Location/URL:** 

- https://github.com/cncf/cnf-testbed/blob/master/artwork/cnf-testbed

**Design:**
![cnftestbedlogo](https://user-images.githubusercontent.com/11701267/65506679-69b9f500-decc-11e9-8ce2-dd03c3ae0ae3.png)

---

Design Tasks:
---
In GitHub:
* [ ]  save files as ```cnftestbed-```

## Horizontal - to be saved as ```cnftestbed-horizontal-``` ... 
  * [x]  black 
      * [ ] .png
      * [ ] .svg
 
  * [x]  color
      * [ ] .png
      * [ ] .svg

  * [x]   white
      * [ ] .png
      * [ ] .svg
  
## Icon - save files as ```cnftestbed-icon-``` ... 
  * [x]  black 
      * [ ] .png
      * [ ] .svg
 
  * [x]  color
      * [ ] .png
      * [ ] .svg

  * [x]   white
      * [ ] .png
      * [ ] .svg

## Stacked - save files as ```cnftestbed-stacked-``` ... 
  * [x]  black 
      * [ ] .png
      * [ ] .svg
 
  * [x]  color
      * [ ] .png
      * [ ] .svg

  * [x]   white
      * [ ] .png
      * [ ] .svg

---

Acceptance Criteria:
---

- [ ]   in folder called Horizontal, the new designs are saved as
     - [ ]  black 
          - [ ]  .png
          - [ ]  .svg
 
     - [ ]  color 
          - [ ]  .png
          - [ ]  .svg

      - [ ]  white 
          - [ ]  .png
          - [ ]  .svg
 

- [ ] in folder called Icon,  the new designs are saved as
     - [ ]  black 
          - [ ]  .png
          - [ ]  .svg
 
     - [ ]  color 
          - [ ]  .png
          - [ ]  .svg

      - [ ]  white 
          - [ ]  .png
          - [ ]  .svg

- [ ] in folder called Stacked, the new designs are saved as
     - [ ]  black 
          - [ ]  .png
          - [ ]  .svg
 
     - [ ]  color 
          - [ ]  .png
          - [ ]  .svg

      - [x]  white 
          - [ ]  .png
          - [ ]  .svg

**Comment by rsiekmann** [comment]
**cnftestbed-stacked-**
SVG






PNG

**Comment by rsiekmann** [comment]
**cnftestbed-horizontal-**

**SVG**
...
**PNG**
![cnftestbed-horizontal-black](https://user-images.githubusercontent.com/26259410/65903821-b85f0780-e382-11e9-8cb4-080481e49f04.png)
![cnftestbed-horizontal-color](https://user-images.githubusercontent.com/26259410/65903822-b85f0780-e382-11e9-8b25-36cd05dcca99.png)
![Uploading cnftestbed-horizontal-white.png…]()

**Comment by rsiekmann** [comment]
**cnftestbed-icon-**

**SVG**
...

**PNG**

![cnftestbed-icon-white](https://user-images.githubusercontent.com/26259410/65904924-1a207100-e385-11e9-87f5-cf4e9224b986.png)
![cnftestbed-icon-black](https://user-images.githubusercontent.com/26259410/65904925-1a207100-e385-11e9-8bc6-9d6640d59fcd.png)
![cnftestbed-icon-color](https://user-images.githubusercontent.com/26259410/65904926-1a207100-e385-11e9-98f2-160056af9c06.png)

**Comment by lixuna** [comment]
Thank you @rsiekmann - Closing issue, as cnf-testbed icons have been added to https://github.com/cncf/artwork/tree/master/other/cnftestbed
