### ISSUE TITLE
Move to split hardware and K8s provisioning with Terraform and Kubespray

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#279]
# Split platform deployment ad provisioning process

- Stage 1 - use Terraform for provisioning Packet hardware based on https://github.com/crosscloudci/infra-provisioning
- Stage 2 - Use Kubespray for K8s deployment, based on https://github.com/crosscloudci/k8s-infra
- Use Ansible for any out-of-band provisioning requirements

**Comment by taylor** [comment]
Documented and tested in commit https://github.com/cncf/cnf-testbed/commit/10b1f77f365d6c26d6c51176a1fa38b12797848d
