### ISSUE TITLE
Updating VPP “base images” to VPP 19.08.1

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#290]

**Comment by michaelspedersen** [comment]
* Dockerfiles updated in [comparison/base_images/container](https://github.com/cncf/cnf-testbed/tree/master/comparison/base_images/container)
* Pre-built images on Dockerhub have been updated and tagged according to VPP version (latest is currently v19.08.1)
* `vppcontainer` image tested on n2,xlarge kubernetes cluster
* `rdma_vppcontainer` image tested on m2.xlarge kubernetes cluster
