### ISSUE TITLE
Fix master & worker variable names in kubernetes-provisioning.env.example

### ISSUE THREAD

**Issue by rihabbanday** [cncf/cnf-testbed#321]
The variable names **MASTER_IPS** and **WORKER_IPS** in the **tools/kubernetes-provisioning.env.example** aren't recognized by the k8sinfra functions (generate_config, etc.) referenced in the docker containers in **tools/kubernetes_provisioning.sh**.  

This scenario can be reproduced in a non-Packet environment by setting HOSTS_FILE=${HOSTS_FILE:-$(pwd)/kubernetes-provisioning.env.example} in **tools/kubernetes_provisioning.sh**.

The correct variable names in   **tools/kubernetes-provisioning.env.example** should be **MASTER_HOSTS** and **WORKER_HOSTS** instead.

**Comment by michaelspedersen** [comment]
I believe this is fixed. Closing issue (a new one can be reopened if needed)
