### ISSUE TITLE
Update k8s-infra to dynamically use latest kubespray release

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-testbed#345]
Acceptance Criteria: TBD
---

Feature: Update k8s-infra to dynamically use latest kubespray release

Short description: 
- to add a new feature to the k8s-infra so that it dynamically downloads the latest release of kubespray before Kubernetes provisioning starts
- currently the new release is downloaded when the image build starts, change this to download before K8s provisioning starts at runtime

Tasks: 
- [ ] TBD

---

Follow-up enhancement from issue #344

**Comment by michaelspedersen** [comment]
Image has been updated, and CNF Testbed deploy script has been updated to reflect changes
