### ISSUE TITLE
VLAN creation issues deploying cnf-testbed to Packet

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#358]
# VLAN creation issues deploying cnf-testbed to Packet

While attempting to deploy the CNF Testbed platform to Packet the provisioning runs into problems accessing/creating the VLANs.

Reference:
- https://cloud-native.slack.com/archives/CKMJMRK99/p1596362518026500
- https://github.com/cncf/cnf-testbed/tree/master/tools#reproducing-the-ci-environment

![image](https://user-images.githubusercontent.com/26697/90149761-7cd6ed00-dd4a-11ea-9dba-b9065a1c0df3.png)

**Comment by taylor** [comment]
cc: @chengtong321

**Comment by taylor** [comment]
Reposting some relevant slack messages:


@denverwilliams  9 days ago said:

> Hey @chengtong
> It looks like it's outright failing to create the vlans on packet.net.
> This normally means that either the Packet API Key, Project ID, or Project Name is incorrect.
> But because it made it this far my first guess would be the Project Name.
> The Project Name is set by running:
> `export PACKET_PROJECT_NAME='YOUR PACKET PROJECT NAME'`

@taylor added:
> For example: “CNF Sandbox”


@chengtong321  responded:
> thanks, i will check that~

**Comment by taylor** [comment]
On Aug 13th, @chengtong321 said:
> hi，i meet another problem when [deploying], i can not find error details from the log. 

![image](https://user-images.githubusercontent.com/26697/90157678-a5171980-dd53-11ea-93ce-f4a372763344.png)

> here is my setting file

![image](https://user-images.githubusercontent.com/26697/90157705-acd6be00-dd53-11ea-9f30-9892f08278be.png)

**Comment by taylor** [comment]
cc @electrocucaracha @michaelspedersen

**Comment by chengtong321** [comment]
Sorry, I have solved this problem ， there are some errors in my configuration file because of my negligence，thank you so much~
