### ISSUE TITLE
Add diagram to snake and pipeline use cases

### ISSUE THREAD

**Issue by taylor** [cncf/cnf-testbed#361]
Add diagrams to
- https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/3c2n-csc
- https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/3c2n-csp

**Comment by michaelspedersen** [comment]
Updated use case examples with diagrams from previous presentations.
Changes: https://github.com/cncf/cnf-testbed/commit/43a30997ce478ce6f5d809ba7612417780bd3c12

**Comment by michaelspedersen** [comment]
Diagrams have been added
